name: 'criss_cross_varying'
lam_type: 'step'
lam_params: {t_step: 700,
            scale: 0.8,
            val1: [1.1, .000001, 0.8],
            val2: [0.8, .000001, 0.9],}
service_type: 'hyper'
network: [[1,0,1],[0,1,0]]
mu: [[2,0,2],[0,1,0]]
h: [1,1,1]
init_queues: [0, 0, 0]
queue_event_options: [[1., 0, 0.],
                      [0., 0., 0.],
                      [0., 0, 1.],
                      [-1., 1., 0.],
                      [0., -1., 0.],
                      [0., 0., -1.],]
train_T: 10000
test_T: 10000
num_pool: 1

  
